name: path-optimization
channels:
    - conda-forge
dependencies:
    - python=3.12
    - pip
    - pip:
          - jupyterlab
          - numpy
          - pandas
          - matplotlib
          - dwave-ocean-sdk
          - networkx
          - pylatexenc
