name: path-optimization
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - pennylane
    - jupyterlab
    - numpy
    - pandas
    - matplotlib
    - JLDracula
    - dwave-ocean-sdk
    - rustworkx
