name: path-optimization
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - pennylane
    - jupyterlab
    - numpy
    - pandas
    - matplotlib
    - dwave-ocean-sdk
    - rustworkx
    - pennylane-qiskit
    - pylatexenc
    - tqdm
